---
- name: Deploy {{ target }} 
  hosts: "{{ target }}"
  vars:
    ci_cd_namespace: lab-ci-cd
    dev_namespace: lab-dev
    test_namespace: lab-test
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
