---
- name: Deploy {{ target }} 
  hosts: "{{ target }}"
  vars:
    ci_cd_namespace: dhs-ci-cd
    dev_namespace: dhs-dev
    test_namespace: dhs-test
    prod_namespace: dhs-prod
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
