---
- name: Deploy {{ target }} 
  hosts: "{{ target }}"
  vars:
    ci_cd_namespace: yellowdog
    dev_namespace: yellowdog-demo
    test_namespace: yellowdog-test
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
