---
ansible_connection: local
openshift_cluster_content:
- object: app-builds
  content:
  - name: build-parameters
    template: "{{ playbook_dir }}/openshift-templates/jenkins-pipeline-configurations/template.yml"
    params: "{{ playbook_dir }}/params/jenkins-pipeline-configurations/deploy"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - pipeline-build
  - name: java-app-build
    template: "{{ playbook_dir }}/openshift-templates/s2i-app-build/template-no-secrets.yml"
    params: "{{ playbook_dir }}/params/human-review-backend/build"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - java-build
  - name: vue-app-build
    template: "{{ playbook_dir }}/openshift-templates/s2i-app-build/template-no-secrets.yml"
    params: "{{ playbook_dir }}/params/human-review-ui/build"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - vue-build
  - name: build-config-map
    template: "{{ playbook_dir }}/openshift-templates/build-config-map/template.yml"
    params: "{{ playbook_dir }}/params/build-config-map/deploy-test"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - build-config-map
    - build
    - configmap
  - name: human-review-ui-tests
    template: "{{ playbook_dir }}/openshift-templates/jenkins-pipeline-no-ocp-triggers/template.yml"
    params: "{{ playbook_dir }}/params/human-review-ui-tests/build"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - selenium
    - serenity
    - human-review
- object: dev-stage
  content:
  - name: java-app
    template: "{{ playbook_dir }}/openshift-templates/automation-api-hsql/template.yml"
    params: "{{ playbook_dir }}/params/human-review-backend/deploy_dev"
    namespace: "{{ dev_namespace }}"
    tags:
    - java-deploy
  - name: vue-app
    template: "{{ playbook_dir }}/openshift-templates/http-app-deploy/template.yml"
    params: "{{ playbook_dir }}/params/human-review-ui/deploy_dev"
    namespace: "{{ dev_namespace }}"
    tags:
    - vue-deploy
  - name: mysql-dev
    template: "openshift//mysql-persistent"
    params: "{{ playbook_dir }}/params/mysql-persistent/deploy_dev"
    namespace: "{{ dev_namespace }}"
    tags:
    - java-deploy
  - name: mysql-dev-login
    template: "openshift//mysql-persistent"
    params: "{{ playbook_dir }}/params/mysql-persistent/deploy_dev_login"
    namespace: "{{ dev_namespace }}"
    tags:
    - java-deploy
  - name: amq-dev
    template: "{{ playbook_dir }}/openshift-templates/amq63-basic/template.yml"
    params: "{{ playbook_dir }}/params/amq63-basic/deploy_dev"
    namespace: "{{ dev_namespace }}"
    tags:
    - java-deploy
  - name: fabric8-rolebinding
    template: "{{ playbook_dir }}/openshift-templates/fabric8-role-bindings/template.yml"
    params: "{{ playbook_dir }}/params/human-review-backend/fabric8_dev"
    namespace: "{{ dev_namespace }}"
    tags:
    - java-deploy
  - name: fabric8-rolebinding
    template: "{{ playbook_dir }}/openshift-templates/fabric8-role-bindings/template.yml"
    params: "{{ playbook_dir }}/params/human-review-ui/fabric8_dev"
    namespace: "{{ dev_namespace }}"
    tags:
    - vue-deploy
- object: test-stage
  content:  
  - name: mysql-test
    template: "openshift//mysql-persistent"
    params: "{{ playbook_dir }}/params/mysql-persistent/deploy_test"
    namespace: "{{ test_namespace }}"
    tags:
    - java-deploy
  - name: mysql-test-login
    template: "openshift//mysql-persistent"
    params: "{{ playbook_dir }}/params/mysql-persistent/deploy_test_login"
    namespace: "{{ test_namespace }}"
    tags:
    - java-deploy
  - name: amq-test
    template: "{{ playbook_dir }}/openshift-templates/amq63-basic/template.yml"
    params: "{{ playbook_dir }}/params/amq63-basic/deploy_test"
    namespace: "{{ test_namespace }}"
    tags:
    - java-deploy
  - name: java-app
    template: "{{ playbook_dir }}/openshift-templates/automation-api-hsql/template.yml"
    params: "{{ playbook_dir }}/params/human-review-backend/deploy_test"
    namespace: "{{ test_namespace }}"
    tags:
    - java-deploy
  - name: vue-app
    template: "{{ playbook_dir }}/openshift-templates/http-app-deploy/template.yml"
    params: "{{ playbook_dir }}/params/human-review-ui/deploy_test"
    namespace: "{{ test_namespace }}"
    tags:
    - vue-deploy
  - name: fabric8-rolebinding
    template: "{{ playbook_dir }}/openshift-templates/fabric8-role-bindings/template.yml"
    params: "{{ playbook_dir }}/params/human-review-backend/fabric8_test"
    namespace: "{{ test_namespace }}"
    tags:
    - java-deploy
  - name: fabric8-rolebinding
    template: "{{ playbook_dir }}/openshift-templates/fabric8-role-bindings/template.yml"
    params: "{{ playbook_dir }}/params/human-review-ui/fabric8_test"
    namespace: "{{ test_namespace }}"
    tags:
    - vue-deploy
