---
ansible_connection: local
openshift_cluster_content:
- galaxy_requirements: "{{ playbook_dir }}/galaxy_requirements.yml"
- object: selenium-grid
  content:
  - name: selenium-hub
    template: "https://raw.githubusercontent.com/ddavison/selenium-openshift-templates/3c326d918b48d2e2181987d85a9cd3905d3a4174/selenium-hub.yaml"
    namespace: "{{ ci_cd_namespace }}"
    params: "{{ playbook_dir }}/params/selenium/deploy_hub"
    tags:
    - selenium
    - selenium-hub
  - name: selenium-node-chrome-debug
    template: "https://raw.githubusercontent.com/ddavison/selenium-openshift-templates/3c326d918b48d2e2181987d85a9cd3905d3a4174/selenium-node-chrome-debug.yaml"
    namespace: "{{ ci_cd_namespace }}"
    params: "{{ playbook_dir }}/params/selenium/build_chrome"
    tags:
    - selenium
    - selenium-node-chrome-debug
  - name: selenium-node-chrome
    template: "https://raw.githubusercontent.com/ddavison/selenium-openshift-templates/3c326d918b48d2e2181987d85a9cd3905d3a4174/selenium-node-chrome.yaml"
    namespace: "{{ ci_cd_namespace }}"
    params: "{{ playbook_dir }}/params/selenium/build_chrome"
    tags:
    - selenium
    - selenium-node-chrome
  - name: selenium-node-firefox-debug
    template: "https://raw.githubusercontent.com/ddavison/selenium-openshift-templates/3c326d918b48d2e2181987d85a9cd3905d3a4174/selenium-node-firefox-debug.yaml"
    namespace: "{{ ci_cd_namespace }}"
    params: "{{ playbook_dir }}/params/selenium/build_firefox"
    tags:
    - selenium
    - selenium-node-firefox-debug
  - name: selenium-node-firefox
    template: "https://raw.githubusercontent.com/ddavison/selenium-openshift-templates/3c326d918b48d2e2181987d85a9cd3905d3a4174/selenium-node-firefox.yaml"
    namespace: "{{ ci_cd_namespace }}"
    params: "{{ playbook_dir }}/params/selenium/build_firefox"
    tags:
    - selenium
    - selenium-node-firefox
    post_steps:
    - role: "CICDAnsible/roles/openshift-label-by-expression"
      vars:
        target_namespace: labs-ci-cddeven
        name_pattern: ".*selenium.*"
        label: 'app=selenium'
# - object: ci-cd-templates
#   content:
#   - name: jenkins-buildconfig-template
#     file: "{{ playbook_dir }}/openshift-templates/jenkins-pipeline-no-ocp-triggers/template.yml"
#     namespace: "{{ ci_cd_namespace }}"
#     tags:
#     - jenkins
#     - pipeline
# - object: ci-cd-deployments
#   content:
#   - name: sonarqube
#     template: "{{ playbook_dir }}/openshift-templates/sonarqube/template.yml"
#     params: "{{ playbook_dir }}/params/sonarqube/build-and-deploy"
#     namespace: "{{ ci_cd_namespace }}"
#     tags:
#     - sonar
#   - name: sonarqube-postgresql
#     template: "openshift//postgresql-persistent"
#     params: "{{ playbook_dir }}/params/sonarqube/postgresql"
#     namespace: "{{ ci_cd_namespace }}"
#     tags:
#     - sonar
# - object: ci-cd-builds
#   content:
#   - name: jenkins-s2i
#     template: "{{ playbook_dir }}/openshift-templates/jenkins-s2i-build/template.yml"
#     params: "{{ playbook_dir }}/params/jenkins/build"
#     namespace: "{{ ci_cd_namespace }}"
#     tags:
#     - jenkins
#   - name: tool-box
#     template: "{{ playbook_dir }}/openshift-templates/docker-build/template.yml"
#     params: "{{ playbook_dir }}/params/tool-box/build"
#     namespace: "{{ ci_cd_namespace }}"
#     tags:
#       - tool-box
# - object: jenkins-slave-nodes
#   content:
#   - name: jenkins-slave-mvn
#     template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.1/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
#     params: "{{ playbook_dir }}/params/jenkins-slaves/mvn"
#     namespace: "{{ ci_cd_namespace }}"
#     tags:
#     - jenkins-slaves
#     - mvn-slave
#   - name: jenkins-slave-npm
#     template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.1/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
#     params: "{{ playbook_dir }}/params/jenkins-slaves/npm"
#     namespace: "{{ ci_cd_namespace }}"
#     tags:
#     - jenkins-slaves
#     - npm-slave
#   - name: jenkins-slave-zap
#     template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.1/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
#     params: "{{ playbook_dir }}/params/jenkins-slaves/zap"
#     namespace: "{{ ci_cd_namespace }}"
#     tags:
#     - jenkins-slaves
#     - zap-slave
#   - name: jenkins-slave-ansible
#     template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.1/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
#     params: "{{ playbook_dir }}/params/jenkins-slaves/ansible"
#     namespace: "{{ ci_cd_namespace }}"
#     tags:
#       - jenkins-slaves
#       - ansible-slave
#   - name: jenkins-slave-arachni
#     template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.1/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
#     params: "{{ playbook_dir }}/params/jenkins-slaves/arachni"
#     namespace: "{{ ci_cd_namespace }}"
#     tags:
#       - jenkins-slaves
#       - arachni-slave
#   - name: jenkins-slave-gradle
#     template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.1/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
#     params: "{{ playbook_dir }}/params/jenkins-slaves/gradle"
#     namespace: "{{ ci_cd_namespace }}"
#     tags:
#       - jenkins-slaves
#       - gradle-slave
#   - name: jenkins-slave-golang
#     template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.1/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
#     params: "{{ playbook_dir }}/params/jenkins-slaves/golang"
#     namespace: "{{ ci_cd_namespace }}"
#     tags:
#       - jenkins-slaves
#       - golang-slave
#   - name: jenkins-slave-mongodb
#     template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.1/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
#     params: "{{ playbook_dir }}/params/jenkins-slaves/mongodb"
#     namespace: "{{ ci_cd_namespace }}"
#     tags:
#       - jenkins-slaves
#       - mongodb-slave
# - object: ci-cd-deployments
#   content:
#   - name: nexus
#     template: "{{ playbook_dir }}/openshift-templates/nexus/template.yml"
#     params: "{{ playbook_dir }}/params/nexus/deploy"
#     namespace: "{{ ci_cd_namespace }}"
#     tags:
#     - nexus
#     post_steps:
#     - role: "CICDAnsible/roles/configure-nexus"
#   - name: jenkins-persistent
#     template: "{{ playbook_dir }}/openshift-templates/jenkins/jenkins-persistent-template.yml"
#     params: "{{ playbook_dir }}/params/jenkins/deploy"
#     namespace: "{{ ci_cd_namespace }}"
#     tags:
#     - jenkins
    
