---
apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "build-configurations"
  annotations:
    description: >-
      Secret and ConfigMap to be used in Jenkins podTemplates to provide
      values to be used in Jenkins pipelines and agent pods
parameters:
- name: HUMAN_REVIEW_TEST_PASSWORD
  description: A test password to be used when you want to have a successful login
  displayName: Human Review test password
  required: true
  value: Pass1
- name: HUMAN_REVIEW_TEST_USERNAME
  description: A test username to be used when you want to have a successful login
  displayName: Human Review test username
  required: true
  value: User1
- name: HUMAN_REVIEW_REST_BASE_URL
  description: The base URL to be used for testing against the Human Review REST API
  displayName: Human Review REST API base URL
  required: true
  value: http://human-review-backend-yellowdog-test.apps.domino.rht-labs.com/api/v1
- name: HUMAN_REVIEW_UI_BASE_URL
  description: The base URL to be used for testing against the Human Review REST API
  displayName: Human Review REST API base URL
  required: true
  value: http://vue-app-yellowdog-test.apps.domino.rht-labs.com/
objects:
- apiVersion: v1
  stringData:
    regular_password: ${HUMAN_REVIEW_TEST_PASSWORD}
    regular_username: ${HUMAN_REVIEW_TEST_USERNAME}
  kind: Secret
  metadata:
    creationTimestamp: null
    labels:
      app: human-review
      name: build-secrets
    name: build-secrets
  type: Opaque
- apiVersion: v1
  data:
    frontend_url: ${HUMAN_REVIEW_UI_BASE_URL}
    rest_api_url: ${HUMAN_REVIEW_REST_BASE_URL}
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    labels:
      app: human-review
      name: build-config
    name: build-config
