apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: twistlock-scanner
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: 'twistian/alpine:latest'
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source