---
kind: Template
apiVersion: v1
metadata:
  name: http-app-deploy
  annotations:
    openshift.io/display-name: HTTP App Deploy Template
    description: A template to deploy your an App with a HTTP endpoint
    iconClass: icon-cube
    tags: http
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: "${NAME}"
    name: "${NAME}"
  spec: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
  spec:
    replicas: 1
    selector:
      name: "${NAME}"
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          name: "${NAME}"
      spec:
        containers:
        - env:          
          - name: SPRING_PROFILE
            value: prod
          - name: LOGIN_DATABASE
            value: humanreviewdb
          - name: LOGIN_HOST
            value: login-db
          - name: MYSQL_HOST
            value: humanreview-db
          - name: MYSQL_PORT
            value: '3306'
          - name: MYSQL_DATABASE
            value: humanreview
          - name: HUMANREVIEW_DATABASE
            value: humanreview
          - name: MQ_BROKER_AMQP
            value: humanreview-amq-amqp
          - name: MQ_PORT_AMQP
            value: '5672'
          - name: MQ_BROKER_TCP
            value: humanreview-amq-tcp
          - name: MQ_PORT_TCP
            value: '61616'
          - name: MQ_USERNAME
            valueFrom:
              secretKeyRef:
                key: MQ_USERNAME
                name: humanreview-amq
          - name: MQ_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MQ_PASSWORD
                name: humanreview-amq
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: humanreview-db
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: humanreview-db
          image: "${NAME}"
          imagePullPolicy: Always
          name: "${NAME}"
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources:
            limits:
              cpu: ${APP_CPU_LIMIT}m
              memory: ${APP_MEM_LIMIT}Mi
            requests:
              cpu: ${APP_CPU_REQUEST}m
              memory: ${APP_CPU_REQUEST}Mi
          terminationMessagePath: "/dev/termination-log"
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - "${NAME}"
        from:
          kind: ImageStreamTag
          name: "${NAME}:latest"
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: "${NAME}"
    name: "${NAME}"
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      name: "${NAME}"
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      name: "${NAME}"
    name: "${NAME}"
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: "${NAME}"
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: jenkins_pipeline_edit
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: "${PIPELINES_NAMESPACE}"
  userNames:
  - system:serviceaccount:${PIPELINES_NAMESPACE}:jenkins
- apiVersion: autoscaling/v2beta1
  kind: HorizontalPodAutoscaler
  metadata:
    name: ${NAME}-autoscaler-cpu-mem
  spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: ReplicationController
      name: ${NAME}
    minReplicas: ${{AUTOSCALE_MIN_REPLICAS}}
    maxReplicas: ${{AUTOSCALE_MAX_REPLICAS}}
    metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: ${{AUTOSCALE_AVERAGE_CPU_UTILIZATION}}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: ${{AUTOSCALE_AVERAGE_MEM_UTILIZATION}}
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all objects and the related imagestream.
  required: true
- name: PIPELINES_NAMESPACE
  displayName: Project/Namespace for Jenkins Pipelines
  description: The project/namespace where the Jenkins executing pipelines is deployed.
  required: true
- name: APP_CPU_LIMIT
  displayName: CPU Utilization Limit
  description: The limit on the amout of CPU (in millicores) that a container instance can use
  required: true
  value: '500'
- name: APP_CPU_REQUEST
  displayName: CPU Utilization Request
  description: The minimum amout of CPU (in millicores) that a container instance starts with
  required: true
  value: '200'
- name: APP_MEM_LIMIT
  displayName: MEM Utilization Limit
  description: The limit on the amout of MEM (in Mibibytes) that a container instance can use
  required: true
  value: '2000'
- name: APP_MEM_REQUEST
  displayName: MEM Utilization Request
  description: The minimum amout of MEM (in Mibibytes) that a container instance starts with
  required: true
  value: '1000'
- name: AUTOSCALE_AVERAGE_CPU_UTILIZATION
  displayName: CPU Autoscale Limit
  description: If a container reaches this average CPU utilization, it will trigger autoscale up to the max number of instances
  required: true
  value: '100'
- name: AUTOSCALE_AVERAGE_MEM_UTILIZATION
  displayName: Memory Autoscale Limit
  description: If a container reaches this average memory utilization, it will trigger autoscale up to the max number of instances
  required: true
  value: '100'
- name: AUTOSCALE_MIN_REPLICAS
  displayName: Minimum Replicas
  description: The minimum number of replicas for this application
  required: true
  value: '1'
- name: AUTOSCALE_MAX_REPLICAS
  displayName: Maximum Replicas
  description: The maximum number of replicas that the autoscaler can create
  required: true
  value: '1'
labels:
  template: http-app-deploy-template
